on: push
env:
  APP: hello
jobs:
  one:
    name: One name
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster:
          - dev-fss
          - prod-fss
        app: []
        include:
          - cluster: dev-fss
            app: aareg
          - cluster: dev-fss
            app: dkif
          - cluster: prod-fss
            app: aareg
          - cluster: prod-fss
            app: dkif
    env:
      EXTRA: ${{ matrix.app }}
    steps:
      - name: Dump Github Context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
       
      - name: Dump Env
        env:
          GITHUB_CONTEXT: ${{ toJSON(env) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"

